server:
  port: 8000
  servlet:
    context-path: /boot
spring:
  dataSource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: etoak
    hikari:
      maximum-pool-size: 50
  thymeleaf:
    cache: false
    encoding: UTF-8
mybatis:
  mapper-location: classpath:mappers/*.xml
  type-aliases-packages: com.etoak.bean
pagehelper:
  reasonable: true

